class CreateLocationTypes < ActiveRecord::Migration
  def up
    create_table :location_types do |t|
      t.string :name
      t.string :description

      t.timestamps
    end
    
    LocationType.reset_column_information
    
    LocationType.create(name: 'origin', description: 'The player spawn location if not tied to a bed. May have a bonus chest.')
    LocationType.create(name: 'home', description: 'The player\'s home base is at this location.')
    LocationType.create(name: 'village', description: 'A natural village generated by the system.')
    LocationType.create(name: 'fake village', description: 'A village created and populated by the player.')
    LocationType.create(name: 'dungeon', description: 'A dungeon generated by the system.')
    LocationType.create(name: 'mine shaft', description: 'A natural mine shaft generated by the system.')
    LocationType.create(name: 'player mine', description: 'A mining area created by the player.')
    LocationType.create(name: 'wolves', description: 'Wolves can be found near this location.')
    LocationType.create(name: 'ocelots', description: 'Ocelots can be found near this location.')
    LocationType.create(name: 'horses', description: 'Horses can be found near this location.')
    LocationType.create(name: 'cows', description: 'Cows can be found near this location.')
    LocationType.create(name: 'pigs', description: 'Pigs can be found near this location.')
    LocationType.create(name: 'chickens', description: 'Chickens can be found near this location.')
    LocationType.create(name: 'mobs', description: 'Mobs can be found near this location.')
    LocationType.create(name: 'witch hut', description: 'A witch hut can be found at this location.')
    LocationType.create(name: 'stronghold', description: 'A stronghold can be found at this location.')
    LocationType.create(name: 'water temple', description: 'A water temple can be found at this location.')
    LocationType.create(name: 'desert temple', description: 'A desert temple can be found at this location.')
    LocationType.create(name: 'jungle temple', description: 'A jungle temple can be found at this location.')
    LocationType.create(name: 'igloo', description: 'An igloo can be found at this location.')
    LocationType.create(name: 'slimes', description: 'Slimes can be found near this location.')
    LocationType.create(name: 'biome', description: 'A specific biome is near this location.')
    LocationType.create(name: 'misc', description: 'Miscellaneous feature can be found at this location (see location notes, if applicable).')
  end
  
  def down
    drop_table :location_types
  end
end
